### ISSUE TITLE
Austausch möglich?

### ISSUE THREAD

**Issue by p-wegmueller** [sinast3000/RGAP#1]
Liebe Sina,
endlich habe ich mich in den letzten Tagen etwas vertiefter mit RGAP auseinandersetzen können. Du hast hier wirklich tolle Arbeit geleistet. Ich konnte zumindest in die Nähe kommen der Ergebnisse aus dem Excel-Plugin. Nun habe ich allerdings immer noch gewisse offene Fragen und auch ein paar Rückmeldungen. Was denkst du, hättest du mal Zeit für einen Austausch? 
LG

**Comment by sinast3000** [comment]
siehe Email ;)
